### ISSUE TITLE
Not depending on `fractal-tasks-core[fractal-tasks]` may introduce import errors

### ISSUE THREAD

**Issue by tcompa** [fmi-basel/gliberal-scMultipleX#113]
For your info, we have spotted the following issue related to how `scMultiplex` depends on `fractal-tasks-core`:
* https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/803

I think it will be fixed or mitigated on the `fractal-task-core` side, but I'm re-raising the issue here to let you know that you may find a `ModuleNotFoundError` due to this reason.

In case this becomes a blocking issue, I think that a temporary solution would be to add `image_registration` as a dependency for `scMultiplex`.

**Comment by jluethi** [comment]
This is now fixed in fractal-tasks-core 1.2.1. The utils function can now be imported as `from fractal_tasks_core.utils import create_well_acquisition_dict` and no extras are required.

I'll create a PR (likely next week) for updating this dependency. It also contains the pydantic V2 switch, which shouldn't be too tricky for this repo I think
